-- 5.2.1
SELECT RM_ID, RM_NAME, RM_LOC, RM_CAP FROM ROOM 
	ORDER BY RM_CAP DESC, RM_NAME ASC;
-- 5.2.2
SELECT U_TYPE, U_NAME, U_ID FROM USERS
	WHERE U_TYPE='U' 
	ORDER BY U_NAME DESC;
-- 5.2.3
SELECT LB_NAME, LB_TYPE,LB_PHONE FROM LABBOY
	WHERE LB_NAME LIKE 'ส%'
	ORDER BY LB_TYPE, LB_NAME;
-- 5.2.4
SELECT DISTINCT RM_CAP FROM ROOM 
	ORDER BY RM_CAP DESC ;
-- 5.2.5
SELECT MIN(RM_CAP) AS MINIMUM_CAPCITY, MAX(RM_CAP) AS MAXIMUM_CAPCITY, SUM(RM_CAP) AS TOTAL_CAPCITY FROM ROOM ;
-- 5.2.6
SELECT LB_ID,LB_NAME,LB_TYPE,LB_EXP_YR FROM LABBOY
	WHERE LB_EXP_YR>=3 AND LB_TYPE='2';
-- 5.2.7
SELECT R.U_ID, RM_ID, USE_DATE, USE_TIN, USE_TOUT FROM USERS U , reservation R
	WHERE U.U_ID = R.U_ID 
	AND USE_DATE = '2003/05/11'
	AND RM_ID = 'A202'
	ORDER BY USE_TIN, U_ID ;
-- 5.2.8
SELECT O.LB_ID, LB_NAME, LB_EXP_YR, OP_DATE FROM LABBOY L, operation O 
	WHERE L.LB_ID = O.LB_ID
	AND OP_DATE = '2003/2/27'
	ORDER BY LB_EXP_YR;
-- 5.2.9
SELECT S.SW_ID, RM_NAME, RM_LOC, DATE_INS FROM SOFTWARE S, ROOM R, installation I
	WHERE S.SW_ID=I.SW_ID
	AND R.RM_ID=I.RM_ID
	AND S.SW_NAME='Microsoft Word' AND S.SW_VER='6.0'
 	ORDER BY DATE_INS;
-- 5.2.10
SELECT LB_TYPE, COUNT(LB_TYPE) AS NUM_IN_TYPE FROM LABBOY
	GROUP BY LB_TYPE ;
-- 5.2.11
SELECT RM_ID, RM_NAME,RM_LOC FROM ROOM
	WHERE RM_ID NOT IN 
		(SELECT RM_ID FROM reservation)
	ORDER BY RM_NAME;
-- 5.2.12
SELECT U.U_ID, U_NAME,U_TYPE,RM_ID FROM USERS U, reservation R 
	WHERE U.U_ID=R.U_ID
	AND RM_ID = 'A202'
	AND U_TYPE = 'S'
	ORDER BY U_NAME;
-- 5.2.13
SELECT U_ID, RV_DATE, L.LB_ID,RM_ID FROM reservation R, LABBOY L
	WHERE L.LB_ID = R.LB_ID
	AND LB_TYPE='2';
-- 5.2.14
SELECT RM_ID, OP_DATE, W_TOUT-W_TIN AS HOURS FROM operation O, PERIOD P 
	WHERE P.G_ID=O.G_ID
	AND OP_DATE>'02/20/2003' AND OP_DATE<'03/10/2003'
	AND LB_ID IN
		(SELECT LB_ID FROM LABBOY WHERE LB_NAME = 'สกุณา เรียนเก่ง')
	ORDER BY RM_ID DESC;
-- 5.2.15
SELECT RV_DATE, USE_DATE, RM_NAME, U_NAME, LB_NAME FROM LABBOY L, USERS U, reservation RE, ROOM R 
	WHERE L.LB_ID = RE.LB_ID AND U.U_ID = RE.U_ID AND R.RM_ID = RE.RM_ID
	AND RE.RM_ID = 'C302'
	ORDER BY USE_DATE ;
-- 5.2.16
SELECT  L.LB_ID, LB_NAME , COUNT(*) AS WORK_DAY FROM LABBOY L, operation O 
	WHERE L.LB_ID = O.LB_ID
	AND L.LB_ID IN ('1028', '1247', '3006')
	AND OP_DATE BETWEEN '2/1/2003' AND '2/28/2003'
	GROUP BY L.LB_ID, LB_NAME
	ORDER BY WORK_DAY DESC
-- 5.2.17
SELECT L.LB_ID, LB_NAME, LB_TYPE, LB_EXP_YR, COUNT(*) AS WORK_DAYS FROM LABBOY L, operation O
	WHERE L.LB_ID = O.LB_ID 
	GROUP BY L.LB_ID, LB_NAME, LB_TYPE, LB_EXP_YR
	HAVING COUNT(*) = 3;
-- 5.2.18
SELECT U.U_ID, U_NAME, COUNT(*) AS RESERVE_TIME FROM USERS U, reservation R 
	WHERE U.U_ID = R.U_ID 
	GROUP BY  U.U_ID, U_NAME
	HAVING COUNT(*) > 3;
-- 5.2.19
SELECT R.RM_ID, RM_NAME,COUNT(*) AS RESERVE_TIMES FROM ROOM R, reservation RE 
	WHERE R.RM_ID = RE.RM_ID
	GROUP BY R.RM_ID, RM_NAME
	HAVING COUNT(*)<=ALL (SELECT COUNT(*)
					FROM reservation
					GROUP BY RM_ID);
-- 5.2.20
SELECT L.LB_ID,LB_NAME, COUNT(*) AS OPERATE_TIMES FROM LABBOY L, OPERATION O
	WHERE  L.LB_ID = O.LB_ID
	AND OP_DATE BETWEEN '2/1/2003' AND '2/28/2003'
	GROUP BY L.LB_ID,LB_NAME
	HAVING COUNT(*)>=ALL(SELECT COUNT(*)
					FROM OPERATION
					WHERE OP_DATE BETWEEN '2/1/2003' AND '2/28/2003'
					GROUP BY LB_ID);